version: '3.7'
services:
  db:
    container_name: 'db'
    image: postgres:latest
    ports:
      - '6000:5432'
    volumes:
      - 'volume'
    environment:
      'POSTGRES_PASSWORD' : 'coba'
volumes:
  volume: